---
- name: Standalone containers tests
  block:
    - name: Create tmp directory for custom configurations and preflight binary
      ansible.builtin.tempfile:
        state: directory
        prefix: preflight_tmp_dir.
      register: preflight_tmp_dir

    - name: Copy registry authentication into config folder for standalone flow
      ansible.builtin.copy:
        src: "{{ partner_creds }}"
        dest: "{{ preflight_tmp_dir.path }}/config.json"
        mode: "0644"
      when: partner_creds | length

    # Use custom certificate for self sign registry
    - name: Get custom ca certificate for preflight
      ansible.builtin.include_tasks: prepare_custom_certificate.yml
      when: preflight_custom_ca | length

    # To reuse the functionality for e2e certification when operator is defined
    - name: Run preflight check container in a loop for the standalone container flow
      vars:
        current_operator_image: "{{ c.container_image }}"
        operator:
          name: "{{ current_operator_image.split('/')[-1].split(':')[0].split('@')[0] }}"
          version: "{{ current_operator_image.split(':')[-1] }}"
          pyxis_container_identifier: "{{ c.pyxis_container_identifier | default('') }}"
          create_container_project: "{{ c.create_container_project | default(false) }}"
          short_description: "{{ c.short_description | default(omit) }}"
          pyxis_product_lists: "{{ c.pyxis_product_lists | default(omit) }}"
      ansible.builtin.include_tasks: test_preflight_check_container_one_image.yml
      loop: "{{ preflight_containers_to_certify }}"
      loop_control:
        loop_var: c
      when:
        - not do_container_parallel_test
        - max_images_per_batch <= 1

    - name: "Run preflight checks in batches of {{ max_images_per_batch }}"
      ansible.builtin.include_tasks: test_preflight_container_parallel.yml
      loop: "{{ preflight_containers_to_certify | batch(max_images_per_batch) | list }}"
      loop_control:
        loop_var: batched_images
      when:
        - do_container_parallel_test
        - max_images_per_batch > 1
  always:
    - name: Teardown
      ansible.builtin.include_tasks: teardown.yml
...
